services:
  app:
    container_name: wails_commander_app
    build:
      context: .
      dockerfile: Windows.Dockerfile
    stdin_open: true   # Mantener el stdin abierto para interactuar con el contenedor
    tty: true
    volumes:
      - ./app:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    env_file: "./windows.env"
    command: [ "bash" ]
    dns:
      - 8.8.8.8
      - 8.8.4.4
