services:
  app:
    container_name: wails_commander_app
    build:
      context: .
      dockerfile: Macos.Dockerfile
    stdin_open: true   # Mantener el stdin abierto para interactuar con el contenedor
    tty: true
    volumes:
      - ./app:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - ENV=development
      - DISPLAY=host.docker.internal:0
    network_mode: "host"
    command: [ "bash" ]